runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /$
  static_files: public/index.html
  upload: public/index.html

- url: /archives
  static_files: public/archives/index.html
  upload: public/archives/index.html

- url: /geek-team
  static_files: public/geek-team/index.html
  upload: public/about/index.html

- url: /categories/Du-lich
  static_files: public/story/index.html
  upload: public/story/index.html

- url: /(.*)/$
  static_files: public/\1/index.html
  upload: public/.*/index.html

- url: /(.+)
  static_files: public/\1
  upload: public/(.*)

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
  - ^node_modules\.*
  - ^scaffolds\.*
  - ^source\.*
  - ^themes\.*
